window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.9

cursor:
  style:
    shape: Beam
    blinking: always

  decorations: none

scrolling:
  history: 10000
  multiplier: 3
 
font:
  normal:
    family: Hack Nerd Font
    style: Regular
  size: 10

draw_bold_text_with_bright_color: True

live_config_reload: true

shell:
  program: /usr/bin/zsh

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
